### ISSUE TITLE
最新版本android studio运行不了

### ISSUE THREAD

**Issue by RicardoJiang** [qdsfdhvh/compose-anime-tv#1]
FAILURE: Build failed with an exception.

* What went wrong:
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.

**Comment by qdsfdhvh** [comment]
我用的是这个canary版，小黄标的AS;

下载地址：https://developer.android.com/studio/preview/index.html

![image](https://user-images.githubusercontent.com/17807925/137409127-a22be856-4482-4cf4-aefb-ace54ccc475b.png)
