### ISSUE TITLE
使用 Android Studio 2021.2.1 Canary 5 无法导入项目

### ISSUE THREAD

**Issue by dongfengweixiao** [qdsfdhvh/compose-anime-tv#2]
Unsupported method: LintOptions.getBaseline().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

AS 的具体版本号为：
> Android Studio Chipmunk | 2021.2.1 Canary 5
> Build #AI-212.5457.46.2112.7905983, built on November 11, 2021
> Runtime version: 11.0.12+7-b1504.28-7817840 amd64
> VM: OpenJDK 64-Bit Server VM by Oracle Corporation
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 1280M
> Cores: 4
> Registry: external.system.auto.import.disabled=true

**Comment by qdsfdhvh** [comment]
我把 agp 改到了7.0.3，试试看能不能编译过。

**Comment by dongfengweixiao** [comment]
> 我把 agp 改到了7.0.3，试试看能不能编译过。

将代码pull到最新后测试，可以导入项目，但是编译存储在错误，提示如下：

> compose-anime-tv\app\build\tmp\kapt3\stubs\debug\com\seiko\tv\anime\ui\player\PlayerViewModel.java:14: ����: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class PlayerViewModel extends androidx.lifecycle.ViewModel {
             ^

可能我去Google官网找下 canary 的历史版本可以更快的解决问题。

**Comment by dongfengweixiao** [comment]
> 我把 agp 改到了7.0.3，试试看能不能编译过。

经测试，Google官网提供的最新的canary因为基于idea的版本是2021.2.1，编译过程中存在错误，无法完整导入项目。使用官网最新的beta版本*Bumblebee (2021.1.1) Beta 4*可以导入项目，可以正常编译。
