### ISSUE TITLE
导入项目后没有 com.seiko.compose 的 package

### ISSUE THREAD

**Issue by xxxape** [qdsfdhvh/compose-anime-tv#3]
![image](https://user-images.githubusercontent.com/49482531/144796599-caa78d4e-9690-42c4-a593-a4d4b3b50d6e.png)
这些 import 会报错

**Comment by qdsfdhvh** [comment]
focuskit库使用了submodule依赖了，需要在项目目录下运行：
```
git submodule init
git submodule update
```
具体可以看下这个链接：https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97

**Comment by xxxape** [comment]
已解决，感谢大佬
