### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by K-Smile** [qdsfdhvh/compose-anime-tv#4]
com.seiko.compose.player.TvVideoPlayer，在项目中找不到

**Comment by qdsfdhvh** [comment]
用了submodule，需要把submodule项目拉下来`git submodule update --init --recursive`

**Comment by K-Smile** [comment]
在手机上运行起来黑屏，没有数据

**Comment by K-Smile** [comment]
可以了可以了，谢谢
